#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset:4 -*-

def xen_info_convert(info): 
    data = {}
    for line in info:
        data[line[0]] = line[1:]
    return data

### Xen and Version detection
def inventory_xen_info_version(info): 
    data = xen_info_convert(info).keys()
    if 'version' in data:
	return [(None, None)]

def check_xen_info_version(_no_item, _no_params, info):
    data = xen_info_convert(info)
    return(0, "Xen Hypervisor OK, Version " + "".join(data['version']))

check_info['xen_info.version'] = {
    "inventory_function"	: inventory_xen_info_version,
    "check_function"		: check_xen_info_version,
    "service_description"	: "Xen Version"
}

### Check Virtual Machine UUID and role
def inventory_xen_info_uuid(info):
    data = xen_info_convert(info).keys()
    if 'uuid' in data:
        return [(None, None)]

def check_xen_info_uuid(_no_item, _no_params, info):
    data = xen_info_convert(info)
   
    if "".join(data['uuid']) == "00000000-0000-0000-0000-000000000000":
        result = "Running as dom0"
    else:
        result = "Running as domU: " + "".join(data['uuid'])

    return(0, result)

check_info['xen_info.uuid'] = {
    "inventory_function"	: inventory_xen_info_uuid,
    "check_function"		: check_xen_info_uuid,
    "service_description"	: "Xen Domain Type and UUID"
}
