#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset:4 -*-

def xen_info_convert(info): 
    data = {}
    for line in info:
        data[line[0]] = line[1:]
    return data

### Xen and Version detection
def inventory_xen_info_version(info): 
    data = xen_info_convert(info).keys()
    if 'version' in data:
	return [(None, None)]

def check_xen_info_version(_no_item, _no_params, info):
    data = xen_info_convert(info)
    return(0, "Xen Hypervisor OK, Version " + "".join(data['version']))

check_info['xen_info.version'] = {
    "inventory_function"	: inventory_xen_info_version,
    "check_function"		: check_xen_info_version,
    "service_description"	: "Xen Version"
}

### CPU Info
def inventory_xen_info_cpu(info):
    data = xen_info_convert(info).keys()
    if 'cpu_amount' in data: 
        return [(None, None)]

def check_xen_info_cpu(_no_item, _no_params, info):
    data = xen_info_convert(info)
    return(0, "Xen Node has " + "".join(data['cpu_amount']) + " CPUs available");

check_info['xen_info.cpu'] = {
    "inventory_function"        : inventory_xen_info_cpu,
    "check_function"            : check_xen_info_cpu,
    "service_description"       : "Xen Node CPU stats"
}
